import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.activity.deleteMany();
  await prisma.deal.deleteMany();
  await prisma.lead.deleteMany();
  await prisma.contact.deleteMany();
  await prisma.company.deleteMany();
  await prisma.product.deleteMany();

  await prisma.product.createMany({
    data: [
      {
        id: "prd_barite",
        name: "Barite",
        category: "Industrial Minerals",
        synonyms: ["Barium sulfate", "Drilling grade barite", "BaSO4"],
        hsCode: "251110",
        specsJson: { BaSO4: "90% min", SG: "4.2 min", mesh: "200" }
      },
      {
        id: "prd_sulfur",
        name: "Sulfur",
        category: "Petrochemicals",
        synonyms: ["Sulphur", "Granular sulfur"],
        hsCode: "250300",
        specsJson: { purity: "99.5% min", form: "Granular" }
      },
      {
        id: "prd_urea",
        name: "Urea",
        category: "Fertilizers",
        synonyms: ["Carbamide", "Prilled urea", "46% nitrogen"],
        hsCode: "310210",
        specsJson: { nitrogen: "46%", form: "Prilled/Granular" }
      },
      {
        id: "prd_pp",
        name: "Polypropylene",
        category: "Polymers",
        synonyms: ["PP", "Homo polypropylene", "Raffia grade"],
        hsCode: "390210",
        specsJson: { mfi: "3-12", usage: "Raffia, injection" }
      },
      {
        id: "prd_chickpeas",
        name: "Chickpeas",
        category: "Pulses",
        synonyms: ["Kabuli chickpeas", "Garbanzo"],
        hsCode: "071320",
        specsJson: { caliber: "8-9 mm", moisture: "13% max" }
      },
      {
        id: "prd_lentils",
        name: "Lentils",
        category: "Pulses",
        synonyms: ["Red lentils", "Green lentils", "Masoor"],
        hsCode: "071340",
        specsJson: { moisture: "13% max", admixture: "1% max" }
      },
      {
        id: "prd_wheat",
        name: "Wheat",
        category: "Grains",
        synonyms: ["Milling wheat", "Feed wheat", "12.5 protein wheat"],
        hsCode: "100199",
        specsJson: { protein: "11.5-12.5%", testWeight: "76 kg/hl" }
      },
      {
        id: "prd_sunflower_oil",
        name: "Sunflower Oil",
        category: "Vegetable Oils",
        synonyms: ["Refined sunflower oil", "RSO"],
        hsCode: "151211",
        specsJson: { ffa: "0.1% max", packing: "Flexitank/IBC" }
      },
      {
        id: "prd_methanol",
        name: "Methanol",
        category: "Petrochemicals",
        synonyms: ["Methyl alcohol"],
        hsCode: "290511",
        specsJson: { purity: "99.85% min" }
      },
      {
        id: "prd_bitumen",
        name: "Bitumen 60/70",
        category: "Oil Products",
        synonyms: ["Asphalt", "Penetration grade bitumen"],
        hsCode: "271320",
        specsJson: { penetration: "60-70", softeningPoint: "49-56 C" }
      },
      {
        id: "prd_ammonium_sulfate",
        name: "Ammonium Sulfate",
        category: "Fertilizers",
        synonyms: ["AS fertilizer", "21-0-0-24S"],
        hsCode: "310221",
        specsJson: { nitrogen: "21%", sulfur: "24%" }
      }
    ]
  });

  await prisma.company.createMany({
    data: [
      {
        id: "cmp_anatolia_fze",
        name: "Anatolia Commodities FZE",
        companyType: "TRADER",
        country: "UAE",
        city: "Dubai",
        website: "https://anatoliacommodities.example.com",
        description: "Regional trader active in barite, sulfur, and urea.",
        source: "Gulfood 2025",
        status: "ACTIVE"
      },
      {
        id: "cmp_kazbarite",
        name: "KazBarite Mining LLP",
        companyType: "SUPPLIER",
        country: "Kazakhstan",
        city: "Aktau",
        website: "https://kazbarite.example.kz",
        description: "Producer of drilling grade barite from Western Kazakhstan.",
        source: "Industry referral",
        status: "ACTIVE"
      },
      {
        id: "cmp_uae_chem",
        name: "Gulf Chem Inputs LLC",
        companyType: "BUYER",
        country: "UAE",
        city: "Sharjah",
        website: "https://gulfcheminputs.example.com",
        description: "Importer of sulfur and methanol for blending and downstream sales.",
        source: "Website inquiry",
        status: "ACTIVE"
      },
      {
        id: "cmp_china_agri",
        name: "Qingdao Agri Inputs Co.",
        companyType: "BUYER",
        country: "China",
        city: "Qingdao",
        website: "https://qingdaoagri.example.cn",
        description: "Large fertilizer distributor with regular urea tenders.",
        source: "Broker introduction",
        status: "ACTIVE"
      },
      {
        id: "cmp_turkey_pulses",
        name: "Ankara Pulse Foods A.S.",
        companyType: "BUYER",
        country: "Turkey",
        city: "Ankara",
        website: "https://ankarapulsefoods.example.tr",
        description: "Food processor importing chickpeas and lentils.",
        source: "Anuga contact",
        status: "ACTIVE"
      },
      {
        id: "cmp_india_poly",
        name: "Mumbai Polymer House",
        companyType: "TRADER",
        country: "India",
        city: "Mumbai",
        website: "https://mumbaipolymer.example.in",
        description: "Polypropylene and petrochemicals trader for South Asia.",
        source: "LinkedIn",
        status: "TO_VERIFY"
      },
      {
        id: "cmp_rus_grain",
        name: "Volga Grain Export JSC",
        companyType: "SUPPLIER",
        country: "Russia",
        city: "Rostov-on-Don",
        website: "https://volgagrain.example.ru",
        description: "Exporter of milling wheat and sunflower oil.",
        source: "Trade map",
        status: "ACTIVE"
      },
      {
        id: "cmp_azer_log",
        name: "Caspian Transit Logistics",
        companyType: "LOGISTICS",
        country: "Azerbaijan",
        city: "Baku",
        website: "https://caspiantransit.example.az",
        description: "Rail and multimodal operator for CIS corridor.",
        source: "Referral",
        status: "ACTIVE"
      },
      {
        id: "cmp_egy_feed",
        name: "Nile Feed Industries",
        companyType: "BUYER",
        country: "Egypt",
        city: "Alexandria",
        website: "https://nilefeed.example.eg",
        description: "Import buyer for wheat and oilseeds.",
        source: "Inbound email",
        status: "ACTIVE"
      },
      {
        id: "cmp_broker_cis",
        name: "CIS Commodity Brokerage DMCC",
        companyType: "BROKER",
        country: "UAE",
        city: "Dubai",
        website: "https://cisbroker.example.com",
        description: "Broker desk for sulfur and fertilizers in CIS markets.",
        source: "Conference",
        status: "ACTIVE"
      },
      {
        id: "cmp_pak_pulses",
        name: "Karachi Pulses Importers",
        companyType: "BUYER",
        country: "Pakistan",
        city: "Karachi",
        website: "https://karachipulses.example.pk",
        description: "Importer and wholesaler of lentils and chickpeas.",
        source: "WhatsApp outreach",
        status: "ACTIVE"
      },
      {
        id: "cmp_blacksea_trd",
        name: "BlackSea Trading Hub",
        companyType: "TRADER",
        country: "Georgia",
        city: "Tbilisi",
        website: "https://blackseahub.example.ge",
        description: "Regional trader focused on wheat, sunflower oil, and PP.",
        source: "Referral",
        status: "INACTIVE"
      }
    ]
  });

  await prisma.contact.createMany({
    data: [
      {
        id: "ctc_001",
        companyId: "cmp_anatolia_fze",
        fullName: "Murat Demir",
        position: "Head Trader",
        email: "murat.demir@anatoliacommodities.example.com",
        phone: "+971555100001",
        whatsapp: "+971555100001",
        telegram: "@murat_anatolia",
        notes: "Decision maker for barite and sulfur cargoes."
      },
      {
        id: "ctc_002",
        companyId: "cmp_anatolia_fze",
        fullName: "Aigerim Sarsen",
        position: "Trading Analyst",
        email: "aigerim@anatoliacommodities.example.com",
        phone: "+971555100002",
        whatsapp: "+971555100002",
        telegram: "@aigerimdesk",
        notes: "Collects inquiry specs and prepares comparison sheets."
      },
      {
        id: "ctc_003",
        companyId: "cmp_kazbarite",
        fullName: "Nurlan Akhmetov",
        position: "Export Manager",
        email: "nurlan@kazbarite.example.kz",
        phone: "+77011000001",
        whatsapp: "+77011000001",
        telegram: "@nurlan_kz",
        notes: "Can commit up to 8,000 MT/month barite."
      },
      {
        id: "ctc_004",
        companyId: "cmp_uae_chem",
        fullName: "Yousef Al Hammadi",
        position: "Procurement Lead",
        email: "yousef@gulfcheminputs.example.com",
        phone: "+971506000101",
        whatsapp: "+971506000101",
        telegram: "@yousefchem",
        notes: "Prefers CIF Jebel Ali."
      },
      {
        id: "ctc_005",
        companyId: "cmp_china_agri",
        fullName: "Li Wei",
        position: "Senior Buyer",
        email: "li.wei@qingdaoagri.example.cn",
        phone: "+8653211000101",
        whatsapp: "+8653211000101",
        telegram: "@liwei_qd",
        notes: "Monthly urea volume buyer."
      },
      {
        id: "ctc_006",
        companyId: "cmp_turkey_pulses",
        fullName: "Esra Kaya",
        position: "Import Manager",
        email: "esra.kaya@ankarapulsefoods.example.tr",
        phone: "+903121000101",
        whatsapp: "+905551010101",
        telegram: "@esrakaya",
        notes: "Interested in lentils 25kg bag and bulk."
      },
      {
        id: "ctc_007",
        companyId: "cmp_india_poly",
        fullName: "Ritesh Shah",
        position: "Polymer Trader",
        email: "ritesh@mumbaipolymer.example.in",
        phone: "+912210001010",
        whatsapp: "+919810001010",
        telegram: "@riteshpoly",
        notes: "Needs PP raffia regularly."
      },
      {
        id: "ctc_008",
        companyId: "cmp_rus_grain",
        fullName: "Dmitri Volkov",
        position: "Export Director",
        email: "d.volkov@volgagrain.example.ru",
        phone: "+78632000101",
        whatsapp: "+798800010101",
        telegram: "@volkovgrain",
        notes: "Wheat and sunflower oil allocations."
      },
      {
        id: "ctc_009",
        companyId: "cmp_azer_log",
        fullName: "Orkhan Mammadov",
        position: "Logistics Coordinator",
        email: "orkhan@caspiantransit.example.az",
        phone: "+994121000101",
        whatsapp: "+994501000101",
        telegram: "@orkhanlog",
        notes: "Rail schedules across Caucasus corridor."
      },
      {
        id: "ctc_010",
        companyId: "cmp_egy_feed",
        fullName: "Ahmed Fawzy",
        position: "Grain Buyer",
        email: "ahmed.fawzy@nilefeed.example.eg",
        phone: "+2031000101",
        whatsapp: "+201000010101",
        telegram: "@ahmedgrain",
        notes: "Requires 30k MT wheat quarterly."
      },
      {
        id: "ctc_011",
        companyId: "cmp_broker_cis",
        fullName: "Elena Morozova",
        position: "Broker",
        email: "elena@cisbroker.example.com",
        phone: "+971504440101",
        whatsapp: "+971504440101",
        telegram: "@elenacis",
        notes: "Active in sulfur spot fixtures."
      },
      {
        id: "ctc_012",
        companyId: "cmp_pak_pulses",
        fullName: "Bilal Qureshi",
        position: "Director Imports",
        email: "bilal@karachipulses.example.pk",
        phone: "+92211000101",
        whatsapp: "+923001000101",
        telegram: "@bilalpk",
        notes: "Targets red lentils from CIS."
      },
      {
        id: "ctc_013",
        companyId: "cmp_blacksea_trd",
        fullName: "Nino Beridze",
        position: "Commercial Manager",
        email: "nino@blackseahub.example.ge",
        phone: "+995321000101",
        whatsapp: "+995599100101",
        telegram: "@ninobs",
        notes: "Inactive account but high historical volume."
      },
      {
        id: "ctc_014",
        companyId: "cmp_uae_chem",
        fullName: "Saeed Al Mansoori",
        position: "Operations Manager",
        email: "saeed@gulfcheminputs.example.com",
        phone: "+971506000202",
        whatsapp: "+971506000202",
        telegram: "@saeedops",
        notes: "Focuses on discharge terminal planning."
      },
      {
        id: "ctc_015",
        companyId: "cmp_china_agri",
        fullName: "Zhang Min",
        position: "Tender Coordinator",
        email: "zhang.min@qingdaoagri.example.cn",
        phone: "+8653211000202",
        whatsapp: "+8653211000202",
        telegram: "@zhangmin",
        notes: "Sends tender docs and deadlines."
      },
      {
        id: "ctc_016",
        companyId: "cmp_rus_grain",
        fullName: "Sergey Ivanov",
        position: "Oil Desk Trader",
        email: "s.ivanov@volgagrain.example.ru",
        phone: "+78632000202",
        whatsapp: "+798800020202",
        telegram: "@sergeyoil",
        notes: "Handles sunflower oil drums and flexitanks."
      },
      {
        id: "ctc_017",
        companyId: "cmp_turkey_pulses",
        fullName: "Mehmet Yilmaz",
        position: "Quality Manager",
        email: "mehmet@ankarapulsefoods.example.tr",
        phone: "+903121000202",
        whatsapp: "+905551010202",
        telegram: "@mehmetqa",
        notes: "Strict quality and aflatoxin checks."
      },
      {
        id: "ctc_018",
        companyId: "cmp_kazbarite",
        fullName: "Dinara Sadykova",
        position: "Sales Coordinator",
        email: "dinara@kazbarite.example.kz",
        phone: "+77011000002",
        whatsapp: "+77011000002",
        telegram: "@dinarakz",
        notes: "Shares production and loading windows."
      }
    ]
  });

  await prisma.lead.createMany({
    data: [
      {
        id: "led_001",
        title: "UAE buyer seeks barite 4.2 SG CIF Jebel Ali",
        productId: "prd_barite",
        companyId: "cmp_uae_chem",
        leadType: "BUY",
        volume: 5000,
        unit: "MT",
        price: 128,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Kazakhstan",
        destinationCountry: "UAE",
        sourceName: "WhatsApp",
        sourceUrl: null,
        rawText: "Need 5,000 MT barite SG 4.2, mesh 200, CIF Jebel Ali, shipment May.",
        aiSummary: "Buyer from UAE requests drilling grade barite with clear quality specs. Wants CIF Jebel Ali basis for May shipment.",
        priority: "HIGH",
        status: "NEGOTIATING",
        publishedAt: new Date("2026-03-12T09:00:00Z")
      },
      {
        id: "led_002",
        title: "Kazakh supplier offers sulfur granules FOB Aktau",
        productId: "prd_sulfur",
        companyId: "cmp_kazbarite",
        leadType: "SELL",
        volume: 12000,
        unit: "MT",
        price: 92,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Kazakhstan",
        destinationCountry: "China",
        sourceName: "Email campaign",
        sourceUrl: null,
        rawText: "Available sulfur granules 12k MT monthly, FOB Aktau, prompt loading.",
        aiSummary: "Supplier can commit regular sulfur cargoes from Aktau on FOB basis. Destination discussion open with China interest.",
        priority: "MEDIUM",
        status: "VERIFIED",
        publishedAt: new Date("2026-03-14T11:30:00Z")
      },
      {
        id: "led_003",
        title: "China buyer inquiry for prilled urea CIF Qingdao",
        productId: "prd_urea",
        companyId: "cmp_china_agri",
        leadType: "INQUIRY",
        volume: 25000,
        unit: "MT",
        price: 312,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Middle East",
        destinationCountry: "China",
        sourceName: "Broker desk",
        sourceUrl: "https://broker-board.example.com/urea-qd-23",
        rawText: "Looking for 25k MT prilled urea 46%, CIF Qingdao, shipment split across two vessels.",
        aiSummary: "Large Chinese buyer seeks 25k MT urea CIF Qingdao with shipment split requirement. Execution depends on vessel planning and terminal slots.",
        priority: "HIGH",
        status: "CONTACTED",
        publishedAt: new Date("2026-03-18T08:15:00Z")
      },
      {
        id: "led_004",
        title: "Turkey buyer needs red lentils 20ft container basis",
        productId: "prd_lentils",
        companyId: "cmp_turkey_pulses",
        leadType: "BUY",
        volume: 560,
        unit: "MT",
        price: 665,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Kazakhstan",
        destinationCountry: "Turkey",
        sourceName: "Trade fair",
        sourceUrl: null,
        rawText: "Need red lentils, 560 MT, CFR Mersin, moisture max 13%, prompt shipment.",
        aiSummary: "Turkish processor is actively buying red lentils for Mersin discharge. Quality limits are clear and timeline is short.",
        priority: "HIGH",
        status: "NEGOTIATING",
        publishedAt: new Date("2026-03-20T13:00:00Z")
      },
      {
        id: "led_005",
        title: "Pakistan buyer for chickpeas Kabuli 9mm",
        productId: "prd_chickpeas",
        companyId: "cmp_pak_pulses",
        leadType: "BUY",
        volume: 900,
        unit: "MT",
        price: 735,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Pakistan",
        sourceName: "Direct call",
        sourceUrl: null,
        rawText: "Buyer in Karachi needs 900 MT Kabuli chickpeas 9mm CIF Karachi.",
        aiSummary: "Steady Pakistan buyer seeks CIF Karachi chickpeas with standard Kabuli calibration.",
        priority: "MEDIUM",
        status: "VERIFIED",
        publishedAt: new Date("2026-03-09T10:20:00Z")
      },
      {
        id: "led_006",
        title: "Indian trader looking for PP raffia grade",
        productId: "prd_pp",
        companyId: "cmp_india_poly",
        leadType: "INQUIRY",
        volume: 3000,
        unit: "MT",
        price: 980,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Saudi Arabia",
        destinationCountry: "India",
        sourceName: "LinkedIn DM",
        sourceUrl: null,
        rawText: "Need PP raffia, 3k MT, CFR Nhava Sheva, monthly option possible.",
        aiSummary: "Indian polymer trader requests PP raffia on CFR basis and hints at recurring monthly volume.",
        priority: "MEDIUM",
        status: "NEW",
        publishedAt: new Date("2026-03-22T15:00:00Z")
      },
      {
        id: "led_007",
        title: "Egypt feed mill seeks milling wheat 12.5 protein",
        productId: "prd_wheat",
        companyId: "cmp_egy_feed",
        leadType: "BUY",
        volume: 30000,
        unit: "MT",
        price: 249,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Egypt",
        sourceName: "Email",
        sourceUrl: null,
        rawText: "Need 30,000 MT milling wheat 12.5 protein CIF Alexandria next month.",
        aiSummary: "Large wheat requirement from Egypt with clear protein spec and delivery port. Competitive freight is critical.",
        priority: "HIGH",
        status: "CONTACTED",
        publishedAt: new Date("2026-03-11T07:45:00Z")
      },
      {
        id: "led_008",
        title: "Sunflower oil offer in flexitanks FOB Novorossiysk",
        productId: "prd_sunflower_oil",
        companyId: "cmp_rus_grain",
        leadType: "OFFER",
        volume: 2500,
        unit: "MT",
        price: 1085,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Russia",
        destinationCountry: "Turkey",
        sourceName: "Supplier bulletin",
        sourceUrl: null,
        rawText: "Offer 2,500 MT refined sunflower oil FOB Novorossiysk, flexitank packing.",
        aiSummary: "Supplier offers flexible sunflower oil volume FOB Novorossiysk with flexitank packing option.",
        priority: "MEDIUM",
        status: "NEW",
        publishedAt: new Date("2026-03-23T12:05:00Z")
      },
      {
        id: "led_009",
        title: "Broker enquiry for sulfur to West Coast India",
        productId: "prd_sulfur",
        companyId: "cmp_broker_cis",
        leadType: "INQUIRY",
        volume: 15000,
        unit: "MT",
        price: 99,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Kazakhstan",
        destinationCountry: "India",
        sourceName: "Broker Telegram",
        sourceUrl: null,
        rawText: "Need sulfur cargo 15k MT CFR west coast India, loading from Caspian options.",
        aiSummary: "Broker seeks sulfur cargo with CFR India route and flexible loading options from Caspian basin.",
        priority: "HIGH",
        status: "NEGOTIATING",
        publishedAt: new Date("2026-03-25T09:40:00Z")
      },
      {
        id: "led_010",
        title: "Barite supplier offer with monthly allocation",
        productId: "prd_barite",
        companyId: "cmp_kazbarite",
        leadType: "SELL",
        volume: 8000,
        unit: "MT",
        price: 119,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Kazakhstan",
        destinationCountry: "UAE",
        sourceName: "Supplier call",
        sourceUrl: null,
        rawText: "We can provide 8k MT/month barite FOB Aktau, SG 4.2.",
        aiSummary: "Supplier confirms monthly barite allocation suitable for recurring demand programs.",
        priority: "MEDIUM",
        status: "VERIFIED",
        publishedAt: new Date("2026-03-08T08:30:00Z")
      },
      {
        id: "led_011",
        title: "Ammonium sulfate buyer request in Black Sea",
        productId: "prd_ammonium_sulfate",
        companyId: null,
        leadType: "BUY",
        volume: 5000,
        unit: "MT",
        price: 182,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Turkey",
        destinationCountry: "Georgia",
        sourceName: "Inbound website form",
        sourceUrl: "https://agri-market.example.com/request-881",
        rawText: "Need AS fertilizer 5000 MT FOB Black Sea, fast delivery.",
        aiSummary: "Unlinked buyer inquiry for ammonium sulfate on FOB Black Sea terms.",
        priority: "LOW",
        status: "NEW",
        publishedAt: new Date("2026-03-17T16:10:00Z")
      },
      {
        id: "led_012",
        title: "Methanol spot cargo offer",
        productId: "prd_methanol",
        companyId: "cmp_uae_chem",
        leadType: "OFFER",
        volume: 10000,
        unit: "MT",
        price: 318,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "UAE",
        destinationCountry: "India",
        sourceName: "Email newsletter",
        sourceUrl: null,
        rawText: "Spot methanol cargo 10,000 MT FOB UAE, discharge India ports.",
        aiSummary: "Spot methanol offer from UAE with India destination options. Pricing is market-sensitive.",
        priority: "LOW",
        status: "DEAD",
        publishedAt: new Date("2026-02-28T14:00:00Z")
      },
      {
        id: "led_013",
        title: "Bitumen 60/70 inquiry for Azerbaijan project",
        productId: "prd_bitumen",
        companyId: "cmp_azer_log",
        leadType: "BUY",
        volume: 6000,
        unit: "MT",
        price: 435,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Iran",
        destinationCountry: "Azerbaijan",
        sourceName: "Phone",
        sourceUrl: null,
        rawText: "Need bitumen 60/70 for road project, 6k MT CIF Baku.",
        aiSummary: "Infrastructure-related demand for bitumen with CIF Baku requirement.",
        priority: "MEDIUM",
        status: "CONTACTED",
        publishedAt: new Date("2026-03-19T12:30:00Z")
      },
      {
        id: "led_014",
        title: "Lentils offer from Kazakhstan in 25kg bags",
        productId: "prd_lentils",
        companyId: null,
        leadType: "SELL",
        volume: 1500,
        unit: "MT",
        price: 642,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Kazakhstan",
        destinationCountry: "Pakistan",
        sourceName: "Telegram channel",
        sourceUrl: null,
        rawText: "Offering red lentils 1500 MT FOB Aktau, 25kg PP bags.",
        aiSummary: "Supplier-side lentils offer suitable for Pakistan and Turkey demand pockets.",
        priority: "MEDIUM",
        status: "VERIFIED",
        publishedAt: new Date("2026-03-24T10:25:00Z")
      },
      {
        id: "led_015",
        title: "Sunflower oil buyer request for Egypt",
        productId: "prd_sunflower_oil",
        companyId: "cmp_egy_feed",
        leadType: "BUY",
        volume: 2200,
        unit: "MT",
        price: 1110,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Egypt",
        sourceName: "Email",
        sourceUrl: null,
        rawText: "Need 2200 MT refined sunflower oil CIF Alexandria.",
        aiSummary: "Egyptian buyer seeking refined sunflower oil cargo for Alexandria.",
        priority: "MEDIUM",
        status: "NEW",
        publishedAt: new Date("2026-03-26T09:10:00Z")
      },
      {
        id: "led_016",
        title: "Urea resale offer in Middle East",
        productId: "prd_urea",
        companyId: "cmp_anatolia_fze",
        leadType: "SELL",
        volume: 12000,
        unit: "MT",
        price: 305,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "UAE",
        destinationCountry: "East Africa",
        sourceName: "Trader network",
        sourceUrl: null,
        rawText: "We can resell 12k MT urea FOB UAE, prompt.",
        aiSummary: "Trading desk offers prompt urea resale lot, suitable for East Africa destinations.",
        priority: "LOW",
        status: "NEW",
        publishedAt: new Date("2026-03-15T09:00:00Z")
      },
      {
        id: "led_017",
        title: "Wheat seller targeting Egypt and Turkey",
        productId: "prd_wheat",
        companyId: "cmp_rus_grain",
        leadType: "OFFER",
        volume: 50000,
        unit: "MT",
        price: 246,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Russia",
        destinationCountry: "Egypt",
        sourceName: "Supplier list",
        sourceUrl: null,
        rawText: "Offering 50k MT wheat 12.5 protein FOB Novorossiysk, target Egypt/Turkey.",
        aiSummary: "Large wheat offer suitable for MENA mills with flexible buyer destinations.",
        priority: "HIGH",
        status: "NEGOTIATING",
        publishedAt: new Date("2026-03-27T07:00:00Z")
      },
      {
        id: "led_018",
        title: "Polypropylene inquiry from CIS distributor",
        productId: "prd_pp",
        companyId: "cmp_blacksea_trd",
        leadType: "BUY",
        volume: 1800,
        unit: "MT",
        price: 995,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Saudi Arabia",
        destinationCountry: "Georgia",
        sourceName: "Old account reactivation",
        sourceUrl: null,
        rawText: "Need PP raffia CFR Poti, 1,800 MT.",
        aiSummary: "Former client account resurfaced with moderate PP volume requirement.",
        priority: "LOW",
        status: "DEAD",
        publishedAt: new Date("2026-03-06T13:50:00Z")
      },
      {
        id: "led_019",
        title: "Sulfur monthly tender from India",
        productId: "prd_sulfur",
        companyId: "cmp_india_poly",
        leadType: "BUY",
        volume: 18000,
        unit: "MT",
        price: 101,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Kazakhstan",
        destinationCountry: "India",
        sourceName: "Tender circular",
        sourceUrl: "https://tenders.example.in/sulfur-q2",
        rawText: "Monthly sulfur requirement 18k MT CFR India west coast.",
        aiSummary: "India market tender for recurring sulfur volume with CFR requirement.",
        priority: "HIGH",
        status: "CONTACTED",
        publishedAt: new Date("2026-03-21T10:00:00Z")
      },
      {
        id: "led_020",
        title: "Barite inquiry from drilling services contractor",
        productId: "prd_barite",
        companyId: null,
        leadType: "INQUIRY",
        volume: 2200,
        unit: "MT",
        price: 130,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Morocco",
        destinationCountry: "UAE",
        sourceName: "Website",
        sourceUrl: "https://drill-input.example.com/request/22",
        rawText: "Need barite 4.1+ SG, 2200 MT CIF Abu Dhabi.",
        aiSummary: "Unlinked drilling contractor inquiry for mid-size barite cargo to UAE.",
        priority: "MEDIUM",
        status: "NEW",
        publishedAt: new Date("2026-03-28T11:00:00Z")
      },
      {
        id: "led_021",
        title: "Chickpeas offer from Russia",
        productId: "prd_chickpeas",
        companyId: "cmp_rus_grain",
        leadType: "OFFER",
        volume: 2000,
        unit: "MT",
        price: 710,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Russia",
        destinationCountry: "Turkey",
        sourceName: "Supplier email",
        sourceUrl: null,
        rawText: "Offer chickpeas 9mm, 2000 MT FOB Novorossiysk.",
        aiSummary: "Supplier offer aligns with Turkish and Pakistan pulse demand.",
        priority: "LOW",
        status: "VERIFIED",
        publishedAt: new Date("2026-03-10T08:10:00Z")
      },
      {
        id: "led_022",
        title: "Urea spot inquiry for East Africa",
        productId: "prd_urea",
        companyId: "cmp_anatolia_fze",
        leadType: "BUY",
        volume: 8000,
        unit: "MT",
        price: 309,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Middle East",
        destinationCountry: "Kenya",
        sourceName: "Desk note",
        sourceUrl: null,
        rawText: "Need 8k MT urea CFR Mombasa by April end.",
        aiSummary: "Spot urea requirement to East Africa with strict timeline.",
        priority: "MEDIUM",
        status: "CONTACTED",
        publishedAt: new Date("2026-03-16T14:00:00Z")
      },
      {
        id: "led_023",
        title: "Ammonium sulfate offer from CIS",
        productId: "prd_ammonium_sulfate",
        companyId: "cmp_broker_cis",
        leadType: "OFFER",
        volume: 9000,
        unit: "MT",
        price: 176,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Uzbekistan",
        destinationCountry: "Turkey",
        sourceName: "Broker sheet",
        sourceUrl: null,
        rawText: "AS 21-0-0-24S 9k MT FOB, available from CIS stock.",
        aiSummary: "Brokered AS lot suitable for Turkish seasonal demand.",
        priority: "LOW",
        status: "NEW",
        publishedAt: new Date("2026-03-29T09:30:00Z")
      },
      {
        id: "led_024",
        title: "Bitumen repeat order inquiry",
        productId: "prd_bitumen",
        companyId: "cmp_azer_log",
        leadType: "BUY",
        volume: 4000,
        unit: "MT",
        price: 442,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Iran",
        destinationCountry: "Azerbaijan",
        sourceName: "Repeat client",
        sourceUrl: null,
        rawText: "Follow-up order 4,000 MT bitumen 60/70 CIF Baku.",
        aiSummary: "Repeat infrastructure demand indicates good continuity potential.",
        priority: "MEDIUM",
        status: "CLOSED",
        publishedAt: new Date("2026-03-30T11:45:00Z")
      }
    ]
  });

  await prisma.deal.createMany({
    data: [
      {
        id: "del_001",
        productId: "prd_barite",
        sourceLeadId: "led_001",
        sellerCompanyId: "cmp_kazbarite",
        buyerCompanyId: "cmp_uae_chem",
        volume: 5000,
        unit: "MT",
        price: 126,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Kazakhstan",
        destinationCountry: "UAE",
        stage: "NEGOTIATING",
        notes: "Awaiting final SGS clause and partial prepayment confirmation."
      },
      {
        id: "del_002",
        productId: "prd_urea",
        sourceLeadId: "led_003",
        sellerCompanyId: "cmp_anatolia_fze",
        buyerCompanyId: "cmp_china_agri",
        volume: 25000,
        unit: "MT",
        price: 310,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "UAE",
        destinationCountry: "China",
        stage: "ACTIVE",
        notes: "2-vessel split under discussion with Qingdao port slots."
      },
      {
        id: "del_003",
        productId: "prd_lentils",
        sourceLeadId: "led_004",
        sellerCompanyId: "cmp_anatolia_fze",
        buyerCompanyId: "cmp_turkey_pulses",
        volume: 560,
        unit: "MT",
        price: 658,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Kazakhstan",
        destinationCountry: "Turkey",
        stage: "WON",
        notes: "Contract signed; loading window first week of April."
      },
      {
        id: "del_004",
        productId: "prd_wheat",
        sourceLeadId: "led_007",
        sellerCompanyId: "cmp_rus_grain",
        buyerCompanyId: "cmp_egy_feed",
        volume: 30000,
        unit: "MT",
        price: 247,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Egypt",
        stage: "NEGOTIATING",
        notes: "Freight firm until end of week; LC terms sent to buyer bank."
      },
      {
        id: "del_005",
        productId: "prd_sulfur",
        sourceLeadId: "led_009",
        sellerCompanyId: "cmp_kazbarite",
        buyerCompanyId: "cmp_india_poly",
        volume: 15000,
        unit: "MT",
        price: 98,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Kazakhstan",
        destinationCountry: "India",
        stage: "ACTIVE",
        notes: "Vessel nomination pending from buyer."
      },
      {
        id: "del_006",
        productId: "prd_sunflower_oil",
        sourceLeadId: "led_015",
        sellerCompanyId: "cmp_rus_grain",
        buyerCompanyId: "cmp_egy_feed",
        volume: 2200,
        unit: "MT",
        price: 1105,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Egypt",
        stage: "DRAFT",
        notes: "Buyer requested samples and updated packing specs."
      },
      {
        id: "del_007",
        productId: "prd_pp",
        sourceLeadId: null,
        sellerCompanyId: "cmp_anatolia_fze",
        buyerCompanyId: "cmp_india_poly",
        volume: 2800,
        unit: "MT",
        price: 988,
        currency: "USD",
        incoterms: "CFR",
        originCountry: "Saudi Arabia",
        destinationCountry: "India",
        stage: "LOST",
        notes: "Lost to lower-priced competitor from Far East."
      },
      {
        id: "del_008",
        productId: "prd_chickpeas",
        sourceLeadId: null,
        sellerCompanyId: "cmp_rus_grain",
        buyerCompanyId: "cmp_pak_pulses",
        volume: 900,
        unit: "MT",
        price: 725,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Russia",
        destinationCountry: "Pakistan",
        stage: "COMPLETED",
        notes: "Cargo discharged successfully; quality claim nil."
      },
      {
        id: "del_009",
        productId: "prd_bitumen",
        sourceLeadId: "led_024",
        sellerCompanyId: "cmp_anatolia_fze",
        buyerCompanyId: "cmp_azer_log",
        volume: 4000,
        unit: "MT",
        price: 440,
        currency: "USD",
        incoterms: "CIF",
        originCountry: "Iran",
        destinationCountry: "Azerbaijan",
        stage: "WON",
        notes: "Repeat deal confirmed; vessel laycan fixed."
      },
      {
        id: "del_010",
        productId: "prd_ammonium_sulfate",
        sourceLeadId: null,
        sellerCompanyId: "cmp_broker_cis",
        buyerCompanyId: "cmp_turkey_pulses",
        volume: 5000,
        unit: "MT",
        price: 179,
        currency: "USD",
        incoterms: "FOB",
        originCountry: "Uzbekistan",
        destinationCountry: "Turkey",
        stage: "DRAFT",
        notes: "Awaiting phytosanitary and packing confirmation."
      }
    ]
  });

  await prisma.activity.createMany({
    data: [
      {
        id: "act_001",
        companyId: "cmp_uae_chem",
        contactId: "ctc_004",
        leadId: "led_001",
        type: "CALL",
        note: "Confirmed buyer accepts SG 4.2 and requested latest shipment ETA.",
        nextActionDate: new Date("2026-04-02T09:00:00Z")
      },
      {
        id: "act_002",
        companyId: "cmp_kazbarite",
        contactId: "ctc_003",
        leadId: "led_001",
        dealId: "del_001",
        type: "WHATSAPP",
        note: "Supplier shared fresh lot assay certificates.",
        nextActionDate: new Date("2026-04-01T08:00:00Z")
      },
      {
        id: "act_003",
        companyId: "cmp_china_agri",
        contactId: "ctc_015",
        leadId: "led_003",
        dealId: "del_002",
        type: "EMAIL",
        note: "Received tender addendum with revised discharge sequence.",
        nextActionDate: new Date("2026-04-03T06:30:00Z")
      },
      {
        id: "act_004",
        companyId: "cmp_turkey_pulses",
        contactId: "ctc_006",
        leadId: "led_004",
        dealId: "del_003",
        type: "MEETING",
        note: "Quality and packing finalized, contract execution cleared.",
        nextActionDate: null
      },
      {
        id: "act_005",
        companyId: "cmp_rus_grain",
        contactId: "ctc_008",
        leadId: "led_007",
        dealId: "del_004",
        type: "TASK",
        note: "Collect freight indications for two loading windows.",
        nextActionDate: new Date("2026-04-01T13:00:00Z")
      },
      {
        id: "act_006",
        companyId: "cmp_india_poly",
        contactId: "ctc_007",
        leadId: "led_009",
        dealId: "del_005",
        type: "CALL",
        note: "Buyer requested split pricing for CFR and FOB options.",
        nextActionDate: new Date("2026-04-02T10:00:00Z")
      },
      {
        id: "act_007",
        companyId: "cmp_anatolia_fze",
        contactId: "ctc_001",
        leadId: "led_016",
        type: "NOTE",
        note: "Urea resale window may tighten due upstream plant maintenance.",
        nextActionDate: null
      },
      {
        id: "act_008",
        companyId: "cmp_egy_feed",
        contactId: "ctc_010",
        leadId: "led_015",
        dealId: "del_006",
        type: "EMAIL",
        note: "Sent revised offer with insurance split and laytime terms.",
        nextActionDate: new Date("2026-04-04T09:30:00Z")
      },
      {
        id: "act_009",
        companyId: "cmp_azer_log",
        contactId: "ctc_009",
        leadId: "led_024",
        dealId: "del_009",
        type: "MEETING",
        note: "Client approved second lot after first shipment performance.",
        nextActionDate: null
      },
      {
        id: "act_010",
        companyId: "cmp_broker_cis",
        contactId: "ctc_011",
        leadId: "led_023",
        dealId: "del_010",
        type: "WHATSAPP",
        note: "Broker sent draft packing list and warehouse photos.",
        nextActionDate: new Date("2026-04-03T11:00:00Z")
      },
      {
        id: "act_011",
        companyId: "cmp_pak_pulses",
        contactId: "ctc_012",
        leadId: "led_005",
        type: "CALL",
        note: "Buyer requested alternative payment via confirmed LC at sight.",
        nextActionDate: new Date("2026-04-02T12:00:00Z")
      },
      {
        id: "act_012",
        companyId: "cmp_blacksea_trd",
        contactId: "ctc_013",
        leadId: "led_018",
        type: "NOTE",
        note: "Account still dormant after initial inquiry.",
        nextActionDate: null
      },
      {
        id: "act_013",
        companyId: "cmp_china_agri",
        contactId: "ctc_005",
        leadId: "led_003",
        dealId: "del_002",
        type: "TASK",
        note: "Prepare alternate shipment plan in case of berth delay.",
        nextActionDate: new Date("2026-04-05T08:00:00Z")
      },
      {
        id: "act_014",
        companyId: "cmp_kazbarite",
        contactId: "ctc_018",
        leadId: "led_010",
        type: "EMAIL",
        note: "Received updated production schedule for April and May.",
        nextActionDate: null
      },
      {
        id: "act_015",
        companyId: "cmp_rus_grain",
        contactId: "ctc_016",
        leadId: "led_008",
        type: "WHATSAPP",
        note: "Shared sunflower oil COA for incoming lot.",
        nextActionDate: new Date("2026-04-02T07:00:00Z")
      },
      {
        id: "act_016",
        companyId: "cmp_turkey_pulses",
        contactId: "ctc_017",
        leadId: "led_004",
        dealId: "del_003",
        type: "NOTE",
        note: "Quality manager accepted sample results and signed quality annex.",
        nextActionDate: null
      },
      {
        id: "act_017",
        companyId: "cmp_anatolia_fze",
        contactId: "ctc_002",
        dealId: "del_007",
        type: "TASK",
        note: "Document lessons learned after lost PP bid.",
        nextActionDate: new Date("2026-04-06T10:30:00Z")
      },
      {
        id: "act_018",
        companyId: "cmp_uae_chem",
        contactId: "ctc_014",
        leadId: "led_012",
        type: "NOTE",
        note: "Methanol spot interest paused due storage tank maintenance.",
        nextActionDate: null
      }
    ]
  });

  console.log("Seed completed successfully.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
